### ISSUE TITLE
Proposal: Add new epm install option

### ISSUE THREAD

**Issue by psibi** [typelead/epm#1]
Option name: --eta-patches-directory

If a patches directory is given, then it should use that
directory instead of hitting github eta-hackage repository.
Usecase: For testing incoming PR for patched packages. (See:
https://travis-ci.org/typelead/eta-hackage/builds/170578328 for
more details)

If there is no opposition, I can volunteer to implement this.

**Comment by rahulmutt** [comment]
I thought this would be required after merging in the PR this morning. Go ahead and implement it. It might be a bit tricky to propagate the option across though. Feel free to discuss any hurdles here.

**Comment by rahulmutt** [comment]
Implemented in #3
