### ISSUE TITLE
`epm install` after `epm update` reports the package list is not updated

### ISSUE THREAD

**Issue by JustusAdam** [typelead/epm#24]
I ran `epm update` and after that `epm install --dependencies-only` but it reported the following warning:

```
Warning: The package list for 'git.etlas.eta-lang.org' does not exist. Run
'epm update' to download it.
```

**Comment by rahulmutt** [comment]
1. Delete `~/.epm/config`
2. Delete `~/.epm/packages/` 
3. Run `epm update`

Let me know if that works.

**Comment by JustusAdam** [comment]
Yes, it did. :) Nice.

**Comment by rahulmutt** [comment]
Closing, since it seems to be fixed.
