### ISSUE TITLE
git apply patch in function patchedExtractTarGzFile is not robust

### ISSUE THREAD

**Issue by psibi** [typelead/epm#4]
I was getting a weird error, when I was trying out the `--eta-patches-directory` option. Digging out more, it was happening because git patch was failing and we were not capturing it in the `patchedExtractTarGzFile`. An example demo of the problem:

```
@sibi::jane { /tmp/cabal-tmp-21805 }-> cabal get old-time
@sibi::jane { /tmp/cabal-tmp-21805 }-> cd old-time-1.1.0.3/
@sibi::jane { /tmp/cabal-tmp-21805/old-time-1.1.0.3 }-> git -C . apply --ignore-space-change --ignore-whitespace  ~/github/eta-hackage/patches/old-time-1.1.0.3.patch
/home/sibi/github/eta-hackage/patches/old-time-1.1.0.3.patch:147: trailing whitespace.
-- #endif
/home/sibi/github/eta-hackage/patches/old-time-1.1.0.3.patch:376: trailing whitespace.
                                       wday yday tzname' _ _) =
/home/sibi/github/eta-hackage/patches/old-time-1.1.0.3.patch:524: trailing whitespace.
data {-# CLASS "java.util.Calendar" #-} Calendar = Calendar (Object# Calendar)
/home/sibi/github/eta-hackage/patches/old-time-1.1.0.3.patch:526: trailing whitespace.
-- Calendar.YEAR/DAY_OF_MONTH is constant, so no need for monadic context
/home/sibi/github/eta-hackage/patches/old-time-1.1.0.3.patch:528: trailing whitespace.
foreign import java unsafe "@static @field java.util.Calendar.YEAR" yEAR :: Int
error: patch failed: old-time.cabal:1
error: old-time.cabal: patch does not apply
```

You can see that the patch command failed. Things that we need to do:
- Check if patch command fails and stop the installation there itself. (Note that even though in my case the patch failed midway, the package compiled and installed successfully. But that's just a recipe of disaster, IMO.)
- I'm still not sure why the patch is invalid. Followed the exact steps documented in `eta-hackage` to generate it. Will look more into this soon.

**Comment by rahulmutt** [comment]
I agree on point 1.

On Point 2, `git` hates trailing whitespace, see [here](http://stackoverflow.com/questions/14509950/my-diff-contains-trailing-whitespace-how-to-get-rid-of-it). So make sure you remove it before creating your patch. I have it setup in emacs to automatically delete the trailing whitespace on saving a file. This should be mentioned in the patching docs.

**Comment by psibi** [comment]
I do have this in my emacs init file:

```
(add-hook 'before-save-hook 'delete-trailing-whitespace)
```

It looks like I'm using an old version of hindent and it sneaks in the trailing whitespace.

**Comment by psibi** [comment]
After digging  more into this, I found that the problem is with the diff of the cabal file. Infact, if you remove the entire diff related to the cabal file from the patch, the git apply patch completes successfully. The reason for that is the cabal file has CRLF for indicating the newline (Windows). Producing the patch file on the Linux system is somewhat messing up the format. I have to yet figure out the proper way of producing the patch.

**Comment by rahulmutt** [comment]
Have Git automatically add CLRF for you? See [here](https://help.github.com/articles/dealing-with-line-endings/).
